# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Minchao's Home Page
tagline:          'welcome'
description:      'Test'
url:              https://github.com/minchao-sun
baseurl:          /

author:
  name:           'Minchao Sun'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/minchao-sun
